#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_tracing : require

#include "RayPayload.glsl"
#include "UniformBufferObject.glsl"

layout(binding = 0, set = 0) uniform accelerationStructureEXT Scene;
layout(binding = 1, rgba32f) uniform image2D AccumulationImage;
layout(binding = 2, rgba32f) uniform image2D OutputImage;
layout(binding = 3) readonly uniform UniformBufferObjectStruct { UniformBufferObject Camera; };

layout(location = 0) rayPayloadEXT RayPayload Ray;

void main()
{
    const vec2 pixel = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 uv = (pixel / gl_LaunchSizeEXT.xy) * 2.0 - 1.0;
    const vec4 origin = Camera.ModelViewInverse * vec4(0, 0, 0, 1);
    const vec4 target = Camera.ProjectionInverse * vec4(uv.x, uv.y, 1, 1);
    const vec4 direction = Camera.ModelViewInverse * vec4(normalize(target.xyz), 0);

    Ray.ColorAndDistance = vec4(0);
    Ray.ScatterDirection = vec4(0);
    Ray.SurfaceNormal = vec3(0);
    Ray.RandomSeed = 0;
    traceRayEXT(Scene, gl_RayFlagsOpaqueEXT, 0xff,
                0, 0, 0, origin.xyz, 0.001, direction.xyz, 10000.0, 0);

    imageStore(AccumulationImage, ivec2(gl_LaunchIDEXT.xy),
               vec4(Ray.ColorAndDistance.rgb, 0));
    imageStore(OutputImage, ivec2(gl_LaunchIDEXT.xy),
               vec4(Ray.ColorAndDistance.rgb, 0));
}
